version: '2'

services:
  mymongo:
    image: mongo:latest

  rest-employees-webapp:
    image: rest-employees:dev
    build:
      context: .
      args:
        JAR_FILE: target/rest-employees-0.0.1-SNAPSHOT.jar
    depends_on:
      - mymongo
    ports:
      - 8081:8081
    environment:
      - DB_HOST=mymongo
      - spring.profiles.active=prod,init-data
